apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.27 # kubectl annotate deployment nginx-deployment kubernetes.io/change-cause="image updated to version 1.27" / kubectl rollout history deployment nginx-deployment
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

# kubectl rollout undo deployment nginx-deployment --to-revision=2
